# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Donuts, Simplices, and Quadrics
subtitle: Anuoluwapo Adisa
name: Anuoluwapo Adisa
email: adisaanuoluwapo9@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Let's talk about Geometry, Cameras. Conics, Manifolds
baseurl: "/odarasimi.github.io"
url: "https://odarasimi.github.io" 

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.26.0"
plugins:
  - jekyll-feed
  - jekyll-include-cache

locale: "en-US"
repository: "odarasimi/odarasimi.github.io"

comments:
  provider: "giscus"
  giscus:
    repo_id              : "R_kgDOL4yzKg"
    category_name        : "Announcements"
    category_id          : "DIC_kwDOL4yzKs4CfQsY"
    discussion_term      : "title" # segment comments based on page title
    reactions_enabled    : "1"
    theme                : "light"

# Uncomment below for analytics
# analytics:
#   provider: "google-gtag"
#   google:
#     tracking_id: ""
#     anonymize_ip: true 

author:
  name: "Anuoluwapo Adisa"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Loves banana cake" # Note: Markdown is allowed
  location: "Lagos, NG"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin-in"
      url: "https://www.linkedin.com/in/anuoluwapo-adisa-290354123/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/odarasimi"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin-in"
      url: "https://www.linkedin.com/in/anuoluwapo-adisa-290354123/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/odarasimi"

breadcrumbs: true  # disabled by default

# To assign a fallback teaser image used in the “Related Posts” module
# This image can be overridden at anytime by applying the below 2 lines to a document’s YAML Front Matter.
#   header:
#     teaser: /assets/images/my-awesome-post-teaser.jpg
# -----> teaser: /assets/images/500x300.png

# by default the site title is on the masthead anyway.
# -----> masthead_title: "Donuts, Simplices, and Quadrics"
# -----> logo: "/assets/images/88x88.png"



# configure google search at: https://programmablesearchengine.google.com/controlpanel/all.
# google:
#   search_engine_id: YOUR_SEARCH_ENGINE_ID


# For pages that don’t have a header.image assigned in their YAML Front Matter, 
# site.og_image will be used as a fallback. Use your logo, icon, avatar or 
# something else that is meaningful. Just make sure it is placed in the /assets/images/ folder, 
# has a minimum size of 120px by 120px, and is less than 1MB in file size.

# -----> og_image: /assets/images/site-logo.png

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Perhaps add social to google knowledge panel
# social:
#   type:  # Person or Organization (defaults to Person)
#   name:  # If the user or organization name differs from the site's name
#   links:
#     - "https://twitter.com/yourTwitter"
#     - "https://www.facebook.com/yourFacebook"